name: levy_address
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  levy_core:
    git:
      url: https://github.com/andreleitejr/levy_core.git

  levy_dependencies:
    git:
      url: https://github.com/andreleitejr/levy_dependencies.git

  auto_route:
  auto_route_generator:
  flutter_riverpod:
  injectable:
  json_annotation:
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  golden_toolkit: ^0.15.0
